---
name: Verdaccio
description: |
  A lightweight private npm proxy registry (sinopia fork)
version: v1.0.0
category: npm
maintainer: Leonardo Gatica <lgatica@protonmail.com>
projectURL: http://github.com/lgaticaq/verdaccio-rancher
labels:
  io.rancher.orchestration.supported: 'cattle,swarm'
